#!/usr/local/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function(error, response, body) {
  let { document } = (new JSDOM(body)).window;
  // grab all paragraphs and references
  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference")

  // remove any reference occurances in wiki text
  references.forEach(function(reference) {
    reference.remove();
  });
  // print out all of the paragraphs
  paragraphs.forEach(function(paragraph) {
    console.log(paragraph.textContent);
  });
});
